version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing CDK..."
      - npm install -g aws-cdk@latest
      - echo "CDK version:" $(cdk --version)

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory:" $(pwd)
      - echo "Listing files:" && ls -la
      - echo "Environment variables:"
      - echo "AWS_ACCOUNT=$AWS_ACCOUNT"
      - echo "AWS_REGION=$AWS_REGION"
      - echo "ENVIRONMENT=$ENVIRONMENT"
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - cd cdk
      - echo "CDK Bootstrap check..."
      - echo "Checking if bootstrap already exists..."
      - aws s3 ls s3://cdk-hnb659fds-assets-$AWS_ACCOUNT-$AWS_REGION/ || echo "Bootstrap bucket not found"
      - cdk bootstrap --context account=$AWS_ACCOUNT --context region=$AWS_REGION --verbose

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Synthesizing CDK stack..."
      - cdk synth --context env=$ENVIRONMENT --context account=$AWS_ACCOUNT --context region=$AWS_REGION
      - echo "Deploying CDK stack..."
      - cdk deploy --context env=$ENVIRONMENT --context account=$AWS_ACCOUNT --context region=$AWS_REGION --require-approval never

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Getting stack outputs..."
      - aws cloudformation describe-stacks --stack-name KUEssayGradingStack-$ENVIRONMENT --region $AWS_REGION
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'