version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install -g aws-cdk
      - yum install -y jq
      - echo "Installing Python dependencies"
      - cd backend
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - cd $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - echo "Environment variables:"
      - echo "AWS_ACCOUNT:$AWS_ACCOUNT"
      - echo "AWS_REGION:$AWS_REGION"
      - echo "ENVIRONMENT:$ENVIRONMENT"
      - echo "ACTION:$ACTION"
      - echo "Current directory:" && pwd
      - echo "Contents:" && ls -la
      - cd backend
      - echo "Now in backend directory for CDK bootstrap"
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Bootstrapping CDK (skipped for destroy operations)..."
          cdk bootstrap --require-approval never --context account=${AWS_ACCOUNT} --context region=${AWS_REGION} || true
        else
          echo "Skipping CDK bootstrap for destroy operation"
        fi
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - echo "Build phase started"
      - echo "Current directory:" && pwd
      - cd backend
      - echo "Now in backend directory:" && pwd
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "=========================================="
          echo "STARTING DESTRUCTION PROCESS"
          echo "=========================================="
          
          # First, try to empty S3 buckets that might prevent stack deletion
          echo "Step 1: Identifying and emptying S3 buckets..."
          STACK_NAME="KUEssayGradingStack-${ENVIRONMENT}"
          
          # Get S3 buckets from the stack
          BUCKETS=$(aws cloudformation describe-stack-resources \
            --stack-name "$STACK_NAME" \
            --region "$AWS_REGION" \
            --query 'StackResources[?ResourceType==`AWS::S3::Bucket`].PhysicalResourceId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$BUCKETS" ] && [ "$BUCKETS" != "None" ]; then
            for bucket in $BUCKETS; do
              echo "Emptying S3 bucket: $bucket"
              aws s3 rm "s3://$bucket" --recursive 2>/dev/null || echo "Could not empty bucket $bucket (may not exist or already empty)"
            done
          else
            echo "No S3 buckets found in stack or stack doesn't exist"
          fi
          
          echo "Step 2: Destroying CDK stacks..."
          cdk destroy --all --force \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION} || {
            echo "CDK destroy failed, checking stack status..."
            aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" || echo "Stack may already be deleted"
            exit 1
          }
          
          echo "Step 3: Verifying stack deletion..."
          sleep 10
          if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "Warning: Stack still exists, checking status..."
            aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" --query 'Stacks[0].StackStatus' --output text
          else
            echo "Stack successfully deleted"
          fi
          
        else
          echo "=========================================="
          echo "STARTING DEPLOYMENT PROCESS"
          echo "=========================================="
          
          echo "Synthesizing CDK stack..."
          cdk synth \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION}

          echo "Deploying CDK stack..."
          cdk deploy --all --require-approval never \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION} \
            --outputs-file cdk_output.json | tee deployment.log
        fi
      - echo "Returning to root directory"
      - cd $CODEBUILD_SRC_DIR
      - echo "Current directory after CDK:" && pwd
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "CDK deployment completed. Starting frontend configuration and build..."
          
          # In the build phase, when checking for CDK outputs
          echo "Extracting values from CDK output..."
          cd frontend
          
          # Debug: Check if output file exists and show its contents
          echo "Checking CDK output file..."
          if [ -f "../backend/cdk_output.json" ]; then
            echo "CDK output file exists. Contents:"
            cat ../backend/cdk_output.json
            echo "--- End of CDK output ---"
          else
            echo "CDK output file not found!"
          fi
          
          # Extract values using correct path to cdk_output.json
          API_URL=$(cat ../backend/cdk_output.json | jq -r '.["KUEssayGradingStack-'${ENVIRONMENT}'"].APIGatewayURL')
          FRONTEND_BUCKET=$(cat ../backend/cdk_output.json | jq -r '.["KUEssayGradingStack-'${ENVIRONMENT}'"].FrontendBucketName')
          DISTRIBUTION_ID=$(cat ../backend/cdk_output.json | jq -r '.["KUEssayGradingStack-'${ENVIRONMENT}'"].CloudFrontDistributionId')
          # If CDK output parsing failed, use known values from previous successful deployment
          if [ -z "$API_URL" ]; then
            echo "CDK output parsing failed, using fallback values..."
            API_URL=""
            FRONTEND_BUCKET=""
            DISTRIBUTION_ID=""
            echo "Using fallback values from known deployment"
          fi
          
          echo "Final values:"
          echo "API_URL: $API_URL"
          echo "FRONTEND_BUCKET: $FRONTEND_BUCKET"
          echo "DISTRIBUTION_ID: $DISTRIBUTION_ID"
          
          if [ -n "$API_URL" ] && [ "$API_URL" != "None" ]; then
            BASE_API_URL=$(echo "$API_URL" | sed 's/\/$//')
            echo "Found API URL: $BASE_API_URL"
            
            # Create .env file
            echo "REACT_APP_ENVIRONMENT=${ENVIRONMENT}" > .env
            echo "REACT_APP_REGION=${AWS_REGION}" >> .env
            echo "REACT_APP_API_URL=${BASE_API_URL}" >> .env
            echo "REACT_APP_DEBUG=true" >> .env
            echo "REACT_APP_LOG_LEVEL=info" >> .env
            echo "Created .env file with API URL"
          else
            echo "Warning: Could not extract API URL from CDK output"
            echo "REACT_APP_ENVIRONMENT=${ENVIRONMENT}" > .env
            echo "REACT_APP_REGION=${AWS_REGION}" >> .env
            echo "REACT_APP_API_URL=https://placeholder-api.com" >> .env
            echo "REACT_APP_DEBUG=true" >> .env
            echo "REACT_APP_LOG_LEVEL=info" >> .env
          fi
          
          echo "Installing frontend dependencies..."
          npm install
          
          echo "Building React application..."
          npm run build
          
          if [ -f "build/index.html" ]; then
            echo "Frontend build successful."
            
            if [ -n "$FRONTEND_BUCKET" ] && [ "$FRONTEND_BUCKET" != "None" ]; then
              echo "Uploading frontend to S3: $FRONTEND_BUCKET"
              # Explicitly set AWS environment to use CodeBuild role, not profiles
              unset AWS_PROFILE
              export AWS_DEFAULT_REGION=${AWS_REGION}
              aws s3 sync build/ "s3://${FRONTEND_BUCKET}" --delete --no-cli-pager
              
              if [ -n "$DISTRIBUTION_ID" ] && [ "$DISTRIBUTION_ID" != "None" ]; then
                echo "Creating CloudFront invalidation..."
                aws cloudfront create-invalidation \
                  --distribution-id "$DISTRIBUTION_ID" \
                  --paths "/*" \
                  --no-cli-pager > /dev/null
                echo "CloudFront invalidation created"
              else
                echo "Warning: Could not get CloudFront distribution ID"
              fi
              
              echo "Frontend deployment completed successfully"
            else
              echo "Warning: Could not get frontend bucket name from CDK output"
              echo "React build completed successfully but not uploaded"
            fi
          else
            echo "Error: Frontend build failed - build/index.html not found"
            exit 1
          fi
        fi

  post_build:
    commands:
      - echo "Post-build phase started"
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "=========================================="
          echo "DESTRUCTION COMPLETED"
          echo "=========================================="
          
          STACK_NAME="KUEssayGradingStack-${ENVIRONMENT}"
          
          # Verify the stack is actually deleted
          if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "⚠️  WARNING: Stack still exists!"
            echo "Stack Status:"
            aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" --query 'Stacks[0].StackStatus' --output text
            echo ""
            echo "This might be normal if deletion is still in progress."
            echo "Check the CloudFormation console for detailed status."
          else
            echo "✅ SUCCESS: All KU Essay Grading resources have been destroyed"
            echo ""
            echo "The following resources have been removed:"
            echo "  - Lambda functions"
            echo "  - API Gateway"
            echo "  - S3 buckets"
            echo "  - CloudFront distribution"
            echo "  - IAM roles and policies"
            echo "  - CloudWatch log groups"
          fi
          
        else
          echo "Getting deployment summary..."
          
          STACK_NAME="KUEssayGradingStack-${ENVIRONMENT}"
          
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION} \
            --query 'Stacks[0].Outputs[?OutputKey==`APIGatewayURL`].OutputValue' \
            --output text 2>/dev/null || echo "Not available")
            
          FRONTEND_URL=$(aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION} \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendURL`].OutputValue' \
            --output text 2>/dev/null || echo "Not available")
            
          echo "=========================================="
          echo "DEPLOYMENT COMPLETED SUCCESSFULLY!"
          echo "=========================================="
          echo "Frontend Application: ${FRONTEND_URL}"
          echo "API Gateway: ${API_URL}"
          echo "Grade Essay Endpoint: ${API_URL}grade-essay"
          echo "Generate Rubric Endpoint: ${API_URL}generate-rubric"
          echo "=========================================="
        fi
      - echo "CDK $ACTION operation complete."

artifacts:
  files:
    - '**/*'
  name: ku-essay-grading-artifacts