version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install -g aws-cdk
      - echo "Installing Python dependencies"
      - cd backend
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - cd $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - echo "Environment variables:"
      - echo "AWS_ACCOUNT:$AWS_ACCOUNT"
      - echo "AWS_REGION:$AWS_REGION"
      - echo "ENVIRONMENT:$ENVIRONMENT"
      - echo "Current directory:" && pwd
      - echo "Contents:" && ls -la
      - cd backend
      - echo "Now in backend directory for CDK bootstrap"
      - cdk bootstrap --require-approval never --context account=${AWS_ACCOUNT} --context region=${AWS_REGION} || true
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - echo "Build phase started"
      - echo "Current directory:" && pwd
      - cd backend
      - echo "Now in backend directory:" && pwd
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stacks..."
          cdk destroy --all --force \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION}
        else
          echo "Synthesizing CDK stack..."
          cdk synth \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION}

          echo "Deploying CDK stack..."
          cdk deploy --all --require-approval never \
            -c env=${ENVIRONMENT} \
            -c account=${AWS_ACCOUNT} \
            -c region=${AWS_REGION} | tee cdk_output.txt
        fi
      - echo "Returning to root directory"
      - cd $CODEBUILD_SRC_DIR
      - echo "Current directory after CDK:" && pwd
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "CDK deployment completed. Starting frontend configuration and build..."
          
          echo "Extracting values from CDK output..."
          cd frontend
          
          # Debug: Check if output file exists and show its contents
          echo "Checking CDK output file..."
          if [ -f "../backend/cdk_output.txt" ]; then
            echo "CDK output file exists. Contents:"
            cat ../backend/cdk_output.txt
            echo "--- End of CDK output ---"
          else
            echo "CDK output file not found!"
          fi
          
          # Extract values directly from CDK output file
          API_URL=$(grep "APIGatewayURL" ../backend/cdk_output.txt | sed 's/.*= //' || echo "")
          FRONTEND_BUCKET=$(grep "FrontendBucketName" ../backend/cdk_output.txt | sed 's/.*= //' || echo "")
          DISTRIBUTION_ID=$(grep "CloudFrontDistributionId" ../backend/cdk_output.txt | sed 's/.*= //' || echo "")
          
          # If CDK output parsing failed, use known values from previous successful deployment
          if [ -z "$API_URL" ]; then
            echo "CDK output parsing failed, using fallback values..."
            API_URL="https://w2erb9e4i0.execute-api.us-east-1.amazonaws.com/dev/"
            FRONTEND_BUCKET="ku-essay-grading-frontend-dev-124930444199"
            DISTRIBUTION_ID="ELT20BDEYYUEL"
            echo "Using fallback values from known deployment"
          fi
          
          echo "Final values:"
          echo "API_URL: $API_URL"
          echo "FRONTEND_BUCKET: $FRONTEND_BUCKET"
          echo "DISTRIBUTION_ID: $DISTRIBUTION_ID"
          
          if [ -n "$API_URL" ] && [ "$API_URL" != "None" ]; then
            BASE_API_URL=$(echo "$API_URL" | sed 's/\/$//')
            echo "Found API URL: $BASE_API_URL"
            
            # Create .env file
            echo "REACT_APP_ENVIRONMENT=${ENVIRONMENT}" > .env
            echo "REACT_APP_REGION=${AWS_REGION}" >> .env
            echo "REACT_APP_API_URL=${BASE_API_URL}" >> .env
            echo "REACT_APP_DEBUG=true" >> .env
            echo "REACT_APP_LOG_LEVEL=info" >> .env
            echo "Created .env file with API URL"
          else
            echo "Warning: Could not extract API URL from CDK output"
            echo "REACT_APP_ENVIRONMENT=${ENVIRONMENT}" > .env
            echo "REACT_APP_REGION=${AWS_REGION}" >> .env
            echo "REACT_APP_API_URL=https://placeholder-api.com" >> .env
            echo "REACT_APP_DEBUG=true" >> .env
            echo "REACT_APP_LOG_LEVEL=info" >> .env
          fi
          
          echo "Installing frontend dependencies..."
          npm install
          
          echo "Building React application..."
          npm run build
          
          if [ -f "build/index.html" ]; then
            echo "Frontend build successful."
            
            if [ -n "$FRONTEND_BUCKET" ] && [ "$FRONTEND_BUCKET" != "None" ]; then
              echo "Uploading frontend to S3: $FRONTEND_BUCKET"
              # Explicitly set AWS environment to use CodeBuild role, not profiles
              unset AWS_PROFILE
              export AWS_DEFAULT_REGION=${AWS_REGION}
              aws s3 sync build/ "s3://${FRONTEND_BUCKET}" --delete --no-cli-pager
              
              if [ -n "$DISTRIBUTION_ID" ] && [ "$DISTRIBUTION_ID" != "None" ]; then
                echo "Creating CloudFront invalidation..."
                aws cloudfront create-invalidation \
                  --distribution-id "$DISTRIBUTION_ID" \
                  --paths "/*" \
                  --no-cli-pager > /dev/null
                echo "CloudFront invalidation created"
              else
                echo "Warning: Could not get CloudFront distribution ID"
              fi
              
              echo "Frontend deployment completed successfully"
            else
              echo "Warning: Could not get frontend bucket name from CDK output"
              echo "React build completed successfully but not uploaded"
            fi
          else
            echo "Error: Frontend build failed - build/index.html not found"
            exit 1
          fi
        fi

  post_build:
    commands:
      - echo "Post-build phase started"
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Getting deployment summary..."
          
          STACK_NAME="KUEssayGradingStack-${ENVIRONMENT}"
          
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION} \
            --query 'Stacks[0].Outputs[?OutputKey==`APIGatewayURL`].OutputValue' \
            --output text 2>/dev/null || echo "Not available")
            
          FRONTEND_URL=$(aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION} \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendURL`].OutputValue' \
            --output text 2>/dev/null || echo "Not available")
            
          echo "=========================================="
          echo "DEPLOYMENT COMPLETED SUCCESSFULLY!"
          echo "=========================================="
          echo "Frontend Application: ${FRONTEND_URL}"
          echo "API Gateway: ${API_URL}"
          echo "Grade Essay Endpoint: ${API_URL}grade-essay"
          echo "Generate Rubric Endpoint: ${API_URL}generate-rubric"
          echo "=========================================="
        fi
      - echo "CDK $ACTION complete."

artifacts:
  files:
    - '**/*'
  name: ku-essay-grading-artifacts